### ISSUE TITLE
Enumerate rules from old danger repository to be rewritten

### ISSUE THREAD

**Issue by felipesabino** [indigotech/peril#1]
Create issues here to better organize the old rules rewrite from our old repo https://github.com/indigotech/danger in Typescript at `dangerfiles/pr.ts`

**Comment by eiditakahashi** [comment]
## Common

- [ ] Warn if some files/folders to be changed/committed like `.gitignore`, `yarn.lock`, `.travis.yml`
- [ ] `>>>` Strings to make sure rebase was successful
- [ ] Big PRs
- [ ] Warn when no description is provided
- [ ] Warn when Amazon Secret Key is hardcoded
- [ ] Warn when `Dangerfile` was modified
- [ ] Warn when `http://` is used

## Node

- [ ] Warn when `npm install -g` is used
- [ ] Warn when `.env` or `.nvmrc` files are modified
- [ ] Warn when `console.log` is added
- [ ] Warn when `package.json` was modified and `yarn.lock` or `shrinkwrap` was not
- [ ] Warn if node version is different between .travis.yml, .nvmrc, package.json and README (or just warn if node version has change just in one of these locations)
- [ ] At packages.json every package should have its version fixed (do not use ^ or ~), or explicitly set the major and minor versions (ie.: 1.2.x)
- [ ] [TypeScript] Warn if using `<any>` as return type.

- [ ] Warn if some files/folders to be changed/committed like `settings.yml.erb`, `Fastfile`
- [ ] Warn when ATS Exception is set in plist
- [ ] Warn when Landscape orientation is set in plist
- [ ] Warn when Facebook ID is hardcoded in plist
- [ ] Warn when pod is being loaded from external git repos
- [ ] Warn when `TODO` is added
- [ ] Warn when `print(“”)` is added
- [ ] Warn when `fatalError` is added

**Comment by felipesabino** [comment]
close due to #5
